export const BUSINESS_INFO = {
  name: "ASHTON TURNER",
  email: "VickyMcdonald8462@outlook.com",
  phone: "+1 3075072947",
  address: {
    street: "Jackson Court 6592",
    city: "Littleton",
    state: "Colorado",
    zip: "80130",
    country: "United States",
  },
  fullAddress: "Jackson Court 6592, Littleton, Colorado 80130, United States",
  shortAddress: "Littleton, Colorado",
} as const;

export const CATEGORIES = [
  {
    id: "feeders",
    name: "Smart Feeders",
    description: "Automatic feeding solutions",
    icon: "Utensils",
    href: "/shop/feeders",
  },
  {
    id: "fountains",
    name: "Smart Water Fountains",
    description: "Fresh water, always",
    icon: "Droplets",
    href: "/shop/fountains",
  },
  {
    id: "trackers",
    name: "GPS Trackers & Collars",
    description: "Never lose your pet",
    icon: "MapPin",
    href: "/shop/trackers",
  },
  {
    id: "cameras",
    name: "Pet Cameras",
    description: "Watch & interact remotely",
    icon: "Camera",
    href: "/shop/cameras",
  },
  {
    id: "litter",
    name: "Smart Litter & Sensors",
    description: "Automated hygiene",
    icon: "Sparkles",
    href: "/shop/litter",
  },
  {
    id: "toys",
    name: "Interactive Toys",
    description: "Smart play experiences",
    icon: "Gamepad2",
    href: "/shop/toys",
  },
  {
    id: "health",
    name: "Health Monitoring",
    description: "Track pet wellness",
    icon: "Heart",
    href: "/shop/health",
  },
] as const;

export const PRODUCTS = [
  // Smart Feeders Category (10 products)
  {
    id: "feeder-1",
    name: "PetSafe Smart Feed Automatic Pet Feeder",
    category: "feeders",
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.7,
    reviews: 2847,
    image: "https://s.alicdn.com/@sc04/kf/Hf80078629b244431b6b063ad66bd8759i.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H96fc78161ad84d2b86ebe0c518298f5cy.png?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hee3135d6df7b409d81877e17528fc18fL.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hbf61fa342ca44710ac9d15a8d26ca6f1w.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H9c4aa7c2cb0c4efdabbbd509fca78954L.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H675ea6c1835a4067b2869c5bc1120f83Z.jpg?avif=close&webp=close",
    ],
    badge: "Best Seller",
    shortDescription: "Wi-Fi enabled automatic pet feeder with app control and customizable meal scheduling for dogs and cats up to 15 lbs.",
    fullDescription: "The PetSafe Smart Feed Automatic Pet Feeder revolutionizes pet care with advanced Wi-Fi connectivity and intuitive smartphone app control. Schedule up to 12 meals per day with precise portion control from 1/8 cup to 4 cups per meal. Features include low food alerts, battery backup system, and secure locking lid to prevent pets from accessing food. Compatible with dry and semi-moist food, this feeder ensures your pet receives timely, portion-controlled meals even when you're away. The sleek design fits seamlessly into any home decor while providing reliable, automated feeding solutions.",
    features: [
      "Wi-Fi connectivity with smartphone app control for remote feeding management and meal scheduling",
      "Customizable portion control from 1/8 cup to 4 cups per meal with precise dispensing mechanism",
      "Programmable meal scheduling with up to 12 meals per day for flexible feeding routines",
      "Low food level alerts and notifications sent directly to your mobile device",
      "Battery backup system ensures continuous operation during power outages",
      "Secure locking lid with pet-proof design prevents unauthorized food access",
      "Compatible with dry and semi-moist kibble for versatile feeding options",
      "Large 24-cup capacity food hopper reduces refilling frequency",
      "Easy-to-clean removable food bowl and dishwasher-safe components",
      "Works with pets up to 15 lbs, ideal for small to medium dogs and all cats"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-2",
    name: "WOPET Automatic Pet Feeder with Camera",
    category: "feeders",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.6,
    reviews: 1923,
    image: "https://s.alicdn.com/@sc04/kf/H371866184474499ab15e01da80220419t.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H92d3d65d0b4441e1bf0de62339144beeU.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H46774bfdf06d4a8eaec0708285a04797p.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H0dc662abe8e741bfb6d0c6ff291fbb98l.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hde5a389c9bf2409fb5c96f30827e23d7y.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H8a4c84a6868b49749262a166cfe656b6I.jpg?avif=close&webp=close"
    ],
    badge: "Premium",
    shortDescription: "Advanced automatic pet feeder with built-in HD camera, two-way audio, and voice recording for interactive feeding experiences.",
    fullDescription: "The WOPET Automatic Pet Feeder combines intelligent feeding technology with comprehensive monitoring capabilities. The integrated 1080p HD camera provides real-time video streaming, allowing you to watch your pet during meal times from anywhere. Two-way audio communication enables you to speak to your pet and hear their responses, while voice recording lets you record custom meal call messages. The feeder supports up to 6 meals per day with portion sizes from 1 to 10 portions per meal. The 4-liter capacity food container keeps food fresh with an airtight seal, and the stainless steel bowl is easy to clean and maintain.",
    features: [
      "Built-in 1080p HD camera with night vision for 24/7 monitoring and recording capabilities",
      "Two-way audio communication system for real-time interaction with your pet during feeding",
      "Voice recording feature allows custom meal call messages up to 10 seconds in length",
      "Programmable feeding schedule with up to 6 meals per day and flexible portion control",
      "Portion control system with 1-10 portions per meal, adjustable via smartphone app",
      "4-liter capacity food container with airtight seal to maintain food freshness",
      "Stainless steel removable bowl with dishwasher-safe design for easy maintenance",
      "Low food and power failure alerts with push notifications to your mobile device",
      "Wi-Fi connectivity with secure cloud storage for video recordings and feeding history",
      "Compatible with iOS and Android devices for seamless app integration and control"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-3",
    name: "SureFeed Microchip Pet Feeder",
    category: "feeders",
    price: 179.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviews: 3456,
    image: "https://s.alicdn.com/@sc04/kf/H5f33f2ca0a8f4c90842818aaab830afbA.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H77e9827f4fb54817a58a244cbd54267bP.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H8be0bc2680524039aa11573e695c109cV.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H63b80683688b4e5b9b95ad2a4c433373U.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hf951540f523442cfb5f667cf320228bdr.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H0eb425a95af3483190370f77ed767313f.jpg?avif=close&webp=close"
    ],
    badge: "Top Rated",
    shortDescription: "Microchip-activated pet feeder that only opens for your designated pet, perfect for multi-pet households and special dietary needs.",
    fullDescription: "The SureFeed Microchip Pet Feeder utilizes advanced RFID technology to recognize your pet's unique microchip or collar tag, ensuring only the authorized pet can access their food. This intelligent system prevents food theft in multi-pet households and allows for specialized diets without supervision. The feeder features a secure lid that opens only when your pet approaches, closing automatically after they finish eating. The bowl holds up to 1.2 liters of food and is designed with a low-profile entrance that's comfortable for cats and small dogs. The quiet operation and LED indicators provide clear status feedback without disturbing your pet.",
    features: [
      "Microchip and RFID collar tag recognition technology for secure, personalized access control",
      "Automatic lid opening and closing mechanism activated only by authorized pets",
      "Secure feeding system prevents food theft in multi-pet households with multiple animals",
      "Specialized diet management allows different pets to receive appropriate nutrition",
      "1.2-liter food capacity with easy-to-clean removable bowl and lid components",
      "Low-profile design with comfortable entrance height for cats and small dogs",
      "Quiet operation with smooth motor mechanism that won't startle sensitive pets",
      "LED status indicators display battery level, feeding status, and system diagnostics",
      "Battery-powered operation with 6-month battery life using 4 AA batteries",
      "Compatible with ISO 11784/11785 microchips and SureFlap RFID collar tags"
    ],
    petType: ["cat", "dog"],
  },
  {
    id: "feeder-4",
    name: "Petlibro Automatic Pet Feeder with App Control",
    category: "feeders",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.5,
    reviews: 1678,
    image: "https://s.alicdn.com/@sc04/kf/H719ec293e967460fac92f5c1f257329eS.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H1743a525f048470f9c12680265327977f.png?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Ha21fb8d670ef4828b9070e5ea0aaa00a9.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H955cf1b3e7514f12bc4c4f98d88edf38J.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H8f3302ba556d47e0ba7b65134b7ef460J.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hec11a011a0ab4bb882c3da4fec7627b8E.jpg?avif=close&webp=close"
    ],
    shortDescription: "Affordable Wi-Fi enabled automatic pet feeder with smartphone app, voice recording, and flexible meal scheduling for busy pet owners.",
    fullDescription: "The Petlibro Automatic Pet Feeder offers premium features at an accessible price point, making automated pet feeding available to all pet owners. The Wi-Fi enabled device connects seamlessly to your smartphone, allowing you to schedule meals, monitor feeding activity, and dispense food remotely. The feeder supports up to 10 meals per day with portion sizes ranging from 2 to 10 portions per meal. The 4-liter food container features an airtight design to keep food fresh, while the voice recording function lets you call your pet with a personalized 10-second message. The feeder includes low food alerts, feeding history tracking, and a battery backup system for reliable operation.",
    features: [
      "Wi-Fi connectivity with intuitive smartphone app for iOS and Android devices",
      "Flexible meal scheduling with up to 10 meals per day for customized feeding routines",
      "Adjustable portion control from 2 to 10 portions per meal with precise dispensing accuracy",
      "Voice recording feature with 10-second custom message playback during feeding times",
      "4-liter capacity food container with airtight seal to preserve food freshness and prevent spoilage",
      "Low food level detection with instant push notifications to your mobile device",
      "Feeding history tracking with detailed logs of meal times and portion sizes",
      "Battery backup system ensures continuous operation during power interruptions",
      "Easy-to-clean design with removable food container and dishwasher-safe bowl",
      "Compatible with dry kibble and semi-moist food for versatile feeding options"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-5",
    name: "Arf Pets Automatic Pet Feeder with Portion Control",
    category: "feeders",
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.4,
    reviews: 1234,
    image: "https://s.alicdn.com/@sc04/kf/H7cc08f181c504d9eaf87ef1959e4abecK.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H9b365a484faa4534a7037802221eb2237.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hb9773a7e3e8642e1929d51a1cf20328bV.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H81196da0f767420c935a2462e2de5ecfw.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H97bbf224ec7d42319e0f7029c0de2c2a7.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H797bf8f9c9624f528bdec5e9a39f1d83n.jpg?avif=close&webp=close"
    ],
    shortDescription: "Budget-friendly automatic pet feeder with digital display, portion control, and up to 4 meals per day for reliable automated feeding.",
    fullDescription: "The Arf Pets Automatic Pet Feeder provides essential automated feeding functionality at an affordable price. The digital LCD display makes programming simple and intuitive, allowing you to set up to 4 meals per day with portion sizes from 1/4 cup to 4.5 cups per meal. The 5-liter food container keeps dry kibble fresh, and the programmable timer ensures consistent feeding schedules. The feeder operates on both AC power and battery backup, providing reliability during power outages. The removable food bowl is dishwasher-safe for easy cleaning, and the clear food container allows you to monitor food levels at a glance.",
    features: [
      "Digital LCD display with intuitive programming interface for easy meal scheduling",
      "Programmable timer with up to 4 meals per day for consistent feeding routines",
      "Precise portion control from 1/4 cup to 4.5 cups per meal with reliable dispensing mechanism",
      "5-liter capacity food container with transparent design for easy food level monitoring",
      "Dual power system with AC adapter and 3 D-cell battery backup for uninterrupted operation",
      "Low food indicator with visual and audio alerts when food levels are running low",
      "Removable stainless steel bowl with dishwasher-safe design for convenient cleaning",
      "Locking lid mechanism prevents pets from accessing food between scheduled meals",
      "Compatible with dry kibble of various sizes for versatile feeding applications",
      "Compact design suitable for small to medium-sized pets and limited counter space"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-6",
    name: "Cat Mate C500 5 Meal Digital Pet Feeder",
    category: "feeders",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.3,
    reviews: 987,
    image: "https://s.alicdn.com/@sc04/kf/Hf0896de905a44cd583eb4738441b93ccq.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H179adb000427465d957ab1a6c198b6917.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H4cc0b7998b2747f29e3764a6944c8865r.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hdadd75ee478443d3b620dc88fef5313cZ.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hee86230cb1674c589d9d41e89e8f1bbdI.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hc280976faddd4cd5beaec63977e829edr.jpg?avif=close&webp=close"
    ],
    shortDescription: "Reliable 5-meal automatic pet feeder with digital timer, ice pack compatibility, and individual meal compartments for fresh food storage.",
    fullDescription: "The Cat Mate C500 Digital Pet Feeder features five individual meal compartments, each with its own lid that opens at the programmed time. This innovative design allows you to prepare meals in advance, with each compartment keeping food fresh until its scheduled opening time. The feeder includes ice pack compatibility for wet food, making it ideal for cats and dogs who prefer moist meals. The digital timer can be programmed for up to 5 meals over 48 hours, with each meal opening independently. The clear lids allow you to see meal contents, and the easy-to-clean design ensures hygiene between uses.",
    features: [
      "Five individual meal compartments with independent lid opening mechanisms for precise meal timing",
      "Digital timer programming for up to 5 meals over a 48-hour period with flexible scheduling",
      "Ice pack compatibility for wet food storage, keeping meals fresh and cool until serving time",
      "Clear lid design allows visual inspection of meal contents before scheduled feeding times",
      "Individual compartment locks ensure food remains secure until the programmed opening time",
      "Easy-to-clean removable compartments and lids with dishwasher-safe components",
      "Battery-powered operation with long-lasting battery life for reliable standalone use",
      "Suitable for both dry and wet food, accommodating various pet dietary preferences",
      "Compact design ideal for cats and small dogs with space-efficient storage",
      "Manual override option allows immediate access to meals when needed outside schedule"
    ],
    petType: ["cat", "dog"],
  },
  {
    id: "feeder-7",
    name: "Feed and Go Automatic Pet Feeder with Timer",
    category: "feeders",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.2,
    reviews: 756,
    image: "https://s.alicdn.com/@sc04/kf/H63a77b6f8aaa4fb5a8a953868aacc54an.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H6b363bfa7c4c434cab6e4fa6f95653fco.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hce1cae5da53644a08e8d3bd923e2c0aaS.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hbd90c1f13e1c44e284fa7f0e6e46909dU.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H96207ed076a040b7b0baf33c81259098K.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H0c5417b97b9d4ccbbcef6ffdaf559b0c2.jpg?avif=close&webp=close"
    ],
    shortDescription: "Simple and reliable automatic pet feeder with mechanical timer, portion control, and 4.5-liter capacity for hassle-free automated feeding.",
    fullDescription: "The Feed and Go Automatic Pet Feeder offers straightforward automated feeding without the complexity of smartphone apps or Wi-Fi connectivity. The mechanical timer system is easy to program, allowing you to set up to 2 meals per day with adjustable portion sizes. The 4.5-liter food container provides ample storage for dry kibble, and the clear design lets you monitor food levels easily. The feeder operates on AC power with battery backup capability, ensuring your pet receives meals even during power outages. The removable bowl is dishwasher-safe, and the simple design makes it perfect for pet owners who prefer uncomplicated solutions.",
    features: [
      "Mechanical timer system with easy-to-use dial interface for simple meal programming",
      "Dual meal scheduling capability with up to 2 meals per day for consistent feeding",
      "Adjustable portion control mechanism with multiple portion size options per meal",
      "4.5-liter capacity food container with transparent design for food level visibility",
      "AC power operation with optional battery backup for reliable power source flexibility",
      "Removable food bowl with dishwasher-safe construction for convenient cleaning",
      "Locking lid system prevents pet access to food between scheduled feeding times",
      "Compatible with dry kibble of various sizes and shapes for versatile food options",
      "Compact and lightweight design suitable for countertop or floor placement",
      "Quiet operation with smooth dispensing mechanism that won't disturb pets or owners"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-8",
    name: "PetSafe Healthy Pet Simply Feed Automatic Feeder",
    category: "feeders",
    price: 129.99,
    originalPrice: 149.99,
    rating: 4.6,
    reviews: 2134,
    image: "https://s.alicdn.com/@sc04/kf/H8f5563bb884e46c299170d363a7323abT.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H27361a5532ec4ae99295e4891c7e81fb2.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hd71e8bfa7d6e4f83a394bc27626dbfb6W.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H39a991e08dcf48298f0ca97ea0928cb2x.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hb8a72449778c4220ac9aa11dbc449bf3E.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H8fd09b0839b44c4b8b912a9c1e9874d6V.jpg?avif=close&webp=close"
    ],
    badge: "Popular",
    shortDescription: "Large-capacity automatic pet feeder with slow feed option, programmable meal scheduling, and 24-cup food storage capacity.",
    fullDescription: "The PetSafe Healthy Pet Simply Feed Automatic Feeder is designed for pets who need larger meal portions and slower eating habits. The feeder features a unique slow-feed option that dispenses food gradually over 15 minutes, helping prevent digestive issues and promoting healthier eating patterns. The programmable timer allows up to 12 meals per day with portion sizes from 1/8 cup to 4 cups per meal. The large 24-cup capacity food container reduces refilling frequency, and the locking lid ensures food stays secure. The feeder includes a low food indicator and operates on both AC power and battery backup for maximum reliability.",
    features: [
      "Slow-feed dispensing mode distributes food over 15 minutes to prevent rapid eating and digestive issues",
      "Large 24-cup capacity food container minimizes refilling frequency for convenient maintenance",
      "Programmable meal scheduling with up to 12 meals per day for flexible feeding routines",
      "Precise portion control from 1/8 cup to 4 cups per meal with accurate dispensing mechanism",
      "Locking lid system with secure closure prevents pets from accessing food between meals",
      "Low food indicator with visual alert system to notify when food levels are running low",
      "Dual power system with AC adapter and battery backup ensures continuous operation",
      "Removable food bowl with dishwasher-safe design for easy cleaning and maintenance",
      "Compatible with dry and semi-moist kibble for versatile feeding applications",
      "Suitable for medium to large dogs and multiple pets with generous food capacity"
    ],
    petType: ["dog"],
  },
  {
    id: "feeder-9",
    name: "eufy Pet Feeder C220 Smart Automatic Feeder",
    category: "feeders",
    price: 139.99,
    originalPrice: 169.99,
    rating: 4.7,
    reviews: 1890,
    image: "https://s.alicdn.com/@sc04/kf/He7102bd2d4b240fab5e98ae96a347844e.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H1d807606e6554b87af30ea5420c295acm.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H0771bf8de0874861862598d631c376d4V.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hee1efc737d134f979901b9eb65437801O.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H8972a84e96fe414e965268b4220c7aeaO.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H3d8f897f31f44e32b6a023a06c8be3e5i.jpg?avif=close&webp=close"
    ],
    badge: "New",
    shortDescription: "Smart Wi-Fi enabled automatic pet feeder with app control, voice recording, and advanced portion management for modern pet care.",
    fullDescription: "The eufy Pet Feeder C220 combines cutting-edge smart technology with reliable feeding functionality. The Wi-Fi enabled device connects to the eufyHome app, providing comprehensive control over meal scheduling, portion sizes, and feeding history. The feeder supports up to 6 meals per day with portion sizes from 1 to 10 portions per meal, giving you precise control over your pet's nutrition. The voice recording feature allows you to record a personalized 10-second message that plays during feeding times. The 4-liter food container features an airtight seal to maintain freshness, and the stainless steel bowl is easy to clean. The feeder includes low food alerts, feeding logs, and battery backup for uninterrupted operation.",
    features: [
      "Wi-Fi connectivity with eufyHome smartphone app for iOS and Android devices",
      "Advanced meal scheduling with up to 6 meals per day and flexible timing options",
      "Precise portion control from 1 to 10 portions per meal with reliable dispensing accuracy",
      "Voice recording capability with 10-second custom message playback during feeding",
      "4-liter capacity food container with airtight seal design to preserve food freshness",
      "Low food detection system with instant push notifications to your mobile device",
      "Comprehensive feeding history tracking with detailed logs and statistics",
      "Battery backup system ensures continuous operation during power interruptions",
      "Stainless steel removable bowl with dishwasher-safe construction for easy maintenance",
      "Compatible with dry kibble and designed for pets of all sizes with versatile applications"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "feeder-10",
    name: "PetSafe Smart Feed Connect Automatic Pet Feeder",
    category: "feeders",
    price: 159.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviews: 2678,
    image: "https://s.alicdn.com/@sc04/kf/Hebaa73a50a554dcb96d028cadb0f4898a.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/Hc905108eb09a49a7ac767362538407d1F.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H59bd6e45a85a489cb7f58ebc0ab7999ae.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H41f37db3b14844f8acd547a7b4fd4c200.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H3678212a11454505b4e03f3ffea0b986t.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H1b536cf70e984af897bd6b1f46464ce2v.jpg?avif=close&webp=close"
    ],
    badge: "Best Seller",
    shortDescription: "Premium Wi-Fi connected automatic pet feeder with advanced app features, meal scheduling, and comprehensive feeding management system.",
    fullDescription: "The PetSafe Smart Feed Connect represents the pinnacle of automated pet feeding technology, offering comprehensive control and monitoring through the PetSafe app. The feeder features advanced Wi-Fi connectivity that enables remote feeding, meal scheduling, and real-time notifications. Schedule up to 12 meals per day with precise portion control from 1/8 cup to 4 cups per meal. The feeder includes a large 24-cup capacity food container, low food alerts, feeding history tracking, and battery backup for reliability. The secure locking lid prevents unauthorized access, and the easy-to-clean design ensures hygiene. The app provides detailed feeding analytics, helping you monitor your pet's eating habits and maintain optimal nutrition.",
    features: [
      "Advanced Wi-Fi connectivity with PetSafe app integration for comprehensive feeding management",
      "Flexible meal scheduling with up to 12 meals per day for customized feeding routines",
      "Precise portion control from 1/8 cup to 4 cups per meal with accurate dispensing technology",
      "Large 24-cup capacity food container reduces refilling frequency for convenient maintenance",
      "Low food level detection with instant push notifications and visual indicators",
      "Comprehensive feeding history tracking with detailed analytics and meal statistics",
      "Battery backup system with power failure alerts ensures continuous operation reliability",
      "Secure locking lid mechanism prevents pet access to food between scheduled meals",
      "Easy-to-clean removable components with dishwasher-safe bowl and food container",
      "Compatible with dry and semi-moist kibble for versatile feeding applications and pet preferences"
    ],
    petType: ["dog", "cat"],
  },
  // Smart Water Fountains Category (10 products)
  {
    id: "fountain-1",
    name: "PetSafe Drinkwell Platinum Pet Fountain",
    category: "fountains",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.6,
    reviews: 3245,
    image: "https://s.alicdn.com/@sc04/kf/H4c30aafa1b0f4c7f95dab1b5d02672b25.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H9953ba01a8fa4af58f8e7462ff9a1720l.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/A087627f7c5a44824bd855c896d5f366fk.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H37e4041290524198aaaac96bb6210cc5c.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H267fda34d563429b84a060e55b15e959T.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Heb42e00f25e843518e2cc694de587a9ab.jpg?avif=close&webp=close",
    ],
    badge: "Best Seller",
    shortDescription: "Large capacity pet fountain with free-falling water stream and replaceable carbon filter for fresh, filtered water circulation.",
    fullDescription: "The PetSafe Drinkwell Platinum Pet Fountain provides a continuous supply of fresh, filtered water for your pets. The free-falling water stream entices pets to drink more, promoting better hydration and overall health. The fountain features a large 168-ounce capacity, making it ideal for multiple pets or larger dogs. The replaceable carbon filter removes bad tastes and odors while the dual-stream design creates an appealing water flow. The quiet submersible pump ensures peaceful operation, and the dishwasher-safe components make cleaning effortless. This fountain is perfect for cats and dogs who prefer running water over stagnant bowls.",
    features: [
      "Large 168-ounce water capacity suitable for multiple pets and extended use without frequent refilling",
      "Free-falling water stream design encourages pets to drink more water for better hydration",
      "Replaceable carbon filter system removes bad tastes, odors, and impurities from tap water",
      "Dual-stream water flow creates appealing visual and auditory stimulation for pets",
      "Quiet submersible pump operates at low noise levels for peaceful home environment",
      "Dishwasher-safe components including reservoir, top dish, and filter housing for easy maintenance",
      "BPA-free materials ensure safe drinking water for your pets' health and wellbeing",
      "Low water indicator alerts when water level drops below recommended minimum",
      "Adjustable flow control allows customization of water stream intensity to pet preferences",
      "Suitable for both cats and dogs of all sizes with accessible drinking height design"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "fountain-2",
    name: "Catit Flower Pet Fountain with Triple Action Filter",
    category: "fountains",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.5,
    reviews: 2156,
    image: "https://s.alicdn.com/@sc04/kf/Hf0fad15289fb4450b51d91eddb97c499e.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H27bfa6caa7ce4c19a80cf1084f56d428V.png?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H10d25507231641c1a3d00c26a2f1627fX.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hd7806c40ddfa439294a7321ba998582e7.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H29baf166a2ed4509abd4bf457dbbdd91h.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Ha4573e4844fa426e810b457424357bec1.jpg?avif=close&webp=close",
    ],
    shortDescription: "Decorative flower-shaped pet fountain with triple-action filter system and adjustable water flow for cats and small dogs.",
    fullDescription: "The Catit Flower Pet Fountain combines functionality with aesthetic appeal, featuring a beautiful flower design that doubles as a water source. The triple-action filter system includes a foam filter to catch hair and debris, a carbon filter to remove bad tastes and odors, and an ion-exchange resin to reduce water hardness. The fountain offers three different water flow settings: gentle bubbling, flower stream, or both combined. With a 100-ounce capacity, this fountain is perfect for single or multiple cats and small dogs. The quiet pump and easy-to-clean design make it a popular choice for pet owners seeking an affordable yet effective hydration solution.",
    features: [
      "Decorative flower-shaped design with adjustable water flow settings for visual appeal and pet interest",
      "Triple-action filter system includes foam, carbon, and ion-exchange resin filters for comprehensive water purification",
      "Three water flow modes: gentle bubbling, flower stream, or combined flow for customizable drinking experience",
      "100-ounce water capacity suitable for single or multiple cats and small dogs",
      "Quiet submersible pump operates silently without disturbing pets or household members",
      "Easy-to-clean design with dishwasher-safe components for convenient maintenance",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "Compact design fits easily on countertops or floors without taking excessive space",
      "Ideal for cats who prefer running water and helps encourage increased water consumption"
    ],
    petType: ["cat"],
  },
  {
    id: "fountain-3",
    name: "Pioneer Pet Raindrop Stainless Steel Pet Fountain",
    category: "fountains",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 1890,
    image: "https://s.alicdn.com/@sc04/kf/Hdfc38fbbdec84bc1a150e23bd4b42a6fm.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H270bbb24517c45e0832f1e8e6ba6e553J.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H9bd04808dbb842f496dee5c54a628933B.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hb0b62307e56e4ac7b8727c3ae3916f9bj.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H18c52c7be4ed4ea89c143353fa5c2d432.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H5071f314b2714946b1097fffb4be0fa6d.jpg?avif=close&webp=close",
    ],
    badge: "Premium",
    shortDescription: "Stainless steel pet fountain with raindrop design, replaceable filter, and quiet pump for hygienic water delivery.",
    fullDescription: "The Pioneer Pet Raindrop Stainless Steel Pet Fountain offers a sleek, modern design combined with superior functionality. The stainless steel construction is naturally antimicrobial, preventing bacteria growth and keeping water fresher longer. The raindrop design creates a gentle water flow that entices pets to drink while the replaceable carbon filter removes impurities and bad tastes. The fountain features a 60-ounce capacity and operates with a whisper-quiet pump. The stainless steel material is easy to clean, dishwasher-safe, and won't retain odors or stains like plastic fountains. This fountain is perfect for health-conscious pet owners who prioritize hygiene and durability.",
    features: [
      "Stainless steel construction provides natural antimicrobial properties to prevent bacteria growth",
      "Raindrop design creates gentle, appealing water flow that encourages increased pet hydration",
      "Replaceable carbon filter removes bad tastes, odors, and impurities from tap water",
      "60-ounce water capacity suitable for single or multiple cats and small to medium dogs",
      "Whisper-quiet submersible pump operates silently without disturbing household activities",
      "Dishwasher-safe stainless steel components make cleaning and maintenance effortless",
      "Non-porous surface prevents odor retention and staining compared to plastic alternatives",
      "Low water level indicator alerts when reservoir needs refilling for continuous operation",
      "Durable construction resists scratches, dents, and wear for long-lasting performance",
      "Suitable for cats and dogs who prefer running water and promotes better hydration habits"
    ],
    petType: ["cat", "dog"],
  },
  {
    id: "fountain-4",
    name: "Veken Pet Fountain 84oz Automatic Water Dispenser",
    category: "fountains",
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 1678,
    image: "https://s.alicdn.com/@sc04/kf/Hf81f463ee0444803afd53e416681457bQ.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H2cfd283a48424742871a1963eededf77r.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H088c68b249974f1ca0a2d4417b1192fcq.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H198752fca4454034b4bf306328c4267b3.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hfac4b1e2cbf74a58b7baabee3a7f91a7w.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hb8e5890b38674bfaa62cf9a3127bd81c4.jpg?avif=close&webp=close",
    ],
    shortDescription: "Budget-friendly automatic pet fountain with 84-ounce capacity, 3-layer filtration system, and quiet operation.",
    fullDescription: "The Veken Pet Fountain provides an affordable solution for keeping your pets hydrated with fresh, filtered water. The 84-ounce capacity ensures your pets have plenty of water throughout the day, reducing the need for frequent refills. The 3-layer filtration system includes a sponge filter to catch hair and debris, activated carbon to remove odors and improve taste, and ion-exchange resin to soften hard water. The fountain features a quiet pump that operates at less than 40 decibels, making it suitable for use in any room. The transparent design allows you to monitor water levels easily, and all components are dishwasher-safe for convenient cleaning.",
    features: [
      "Large 84-ounce water capacity reduces refilling frequency for convenient pet care",
      "3-layer filtration system includes sponge, activated carbon, and ion-exchange resin for comprehensive water purification",
      "Quiet pump operation at less than 40 decibels ensures peaceful home environment",
      "Transparent design allows easy monitoring of water levels and filter condition",
      "Dishwasher-safe components including reservoir, pump, and filter housing for easy maintenance",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "Adjustable water flow control allows customization to pet preferences and drinking habits",
      "Suitable for both cats and dogs of various sizes with accessible drinking height",
      "Budget-friendly price point makes automatic hydration accessible to all pet owners"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "fountain-5",
    name: "Petkit Eversweet 2 Smart WiFi Pet Fountain",
    category: "fountains",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviews: 2134,
    image: "https://s.alicdn.com/@sc04/kf/Haeae4a824cf64db78a63878230b55347z.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/Hff22721227d64409a392f972acd91168h.png?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H3a47390d9ebc484784057a3d3a382980k.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H0f465a909fa14921bd7a5b83394026434.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H04d718a76c9842099d74912944013c10Y.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H87c23eea56004120ad7e35422887b6d2K.png?avif=close&webp=close",
    ],
    badge: "New",
    shortDescription: "Wi-Fi enabled smart pet fountain with app control, water quality monitoring, and automatic cleaning reminders.",
    fullDescription: "The Petkit Eversweet 2 Smart WiFi Pet Fountain brings intelligent hydration management to pet care. The Wi-Fi connectivity allows you to monitor water consumption, filter status, and water quality from your smartphone. The fountain features a 2.5-liter capacity with a unique waterfall design that creates oxygen-rich water. The app sends notifications for low water levels, filter replacement reminders, and cleaning schedules. The fountain includes a 5-layer filtration system with activated carbon, ion-exchange resin, and antibacterial materials. The quiet pump operates at ultra-low noise levels, and the sleek design complements modern home decor.",
    features: [
      "Wi-Fi connectivity with smartphone app for remote monitoring and control of fountain operation",
      "Water quality monitoring system tracks TDS levels and alerts when filter replacement is needed",
      "Automatic cleaning reminders sent to your mobile device based on usage patterns and time",
      "2.5-liter water capacity with waterfall design creates oxygen-rich water for better pet health",
      "5-layer filtration system includes activated carbon, ion-exchange resin, and antibacterial materials",
      "Water consumption tracking provides insights into your pet's daily hydration patterns",
      "Ultra-quiet pump operation at less than 30 decibels for peaceful home environment",
      "Low water level alerts with push notifications to your smartphone for timely refilling",
      "Sleek modern design complements contemporary home decor with space-efficient footprint",
      "Compatible with iOS and Android devices for seamless app integration and smart home connectivity"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "fountain-6",
    name: "PetSafe Drinkwell 360 Pet Fountain",
    category: "fountains",
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 1987,
    image: "https://s.alicdn.com/@sc04/kf/H2b663f20e16f4b7884543d1e6c7de08em.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H5ebfcecbd582475e96351314c70969047.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/H3f5483139fbb4afab13dc2ee61dc09a7l.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H7478784bb405467f9a8756c1398f6c93P.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H4cd6deebb3af4183b9ac1afa0341ccf6X.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hbbea12dd7e0d480e88352c7867fb0524h.jpg?avif=close&webp=close",
    ],
    shortDescription: "Multi-pet fountain with 360-degree water flow, adjustable streams, and large 128-ounce capacity for multiple pets.",
    fullDescription: "The PetSafe Drinkwell 360 Pet Fountain is designed for households with multiple pets, featuring a unique 360-degree water flow system. The fountain allows you to adjust the number of water streams from one to five, accommodating different numbers of pets. With a large 128-ounce capacity, this fountain can serve multiple cats and dogs throughout the day. The replaceable carbon filter removes bad tastes and odors, while the free-falling water stream design encourages pets to drink more. The quiet pump and dishwasher-safe components make maintenance simple, and the low water indicator ensures you never run out of water.",
    features: [
      "360-degree water flow system with adjustable streams from one to five for multi-pet households",
      "Large 128-ounce water capacity suitable for multiple pets and extended use periods",
      "Adjustable stream control allows customization based on number of pets and household needs",
      "Replaceable carbon filter removes bad tastes, odors, and impurities from tap water",
      "Free-falling water stream design encourages increased water consumption for better hydration",
      "Quiet submersible pump operates silently without disturbing pets or household activities",
      "Dishwasher-safe components including reservoir, top dish, and filter housing for easy cleaning",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Suitable for multiple cats and dogs of various sizes with accessible drinking height design"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "fountain-7",
    name: "NPET WF050 Pet Water Fountain with LED Light",
    category: "fountains",
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.3,
    reviews: 1234,
    image: "https://s.alicdn.com/@sc04/kf/H0084ac92b561404084b0887b2aeef61fy.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/Hca3923123dcd44839ee835e502f01f0fb.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hbae5dc54da944de695105f00565faf34P.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H479c540d17124db5bfe6c6ee576716bed.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/He02c2c7ded9f4408b7ea25bee93a7fc79.png?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Ha776c519111a45e4bcba4a64c42b0e1eo.jpg?avif=close&webp=close",
    ],
    shortDescription: "Affordable pet fountain with LED light feature, 2-liter capacity, and 3-stage filtration system for budget-conscious pet owners.",
    fullDescription: "The NPET WF050 Pet Water Fountain offers an economical solution for providing fresh, filtered water to your pets. The fountain features an LED light that illuminates the water stream, making it easier for pets to locate the water source, especially in low-light conditions. With a 2-liter capacity, this fountain is suitable for single or multiple cats and small dogs. The 3-stage filtration system includes a sponge filter, activated carbon, and ion-exchange resin to purify water and remove impurities. The quiet pump operates efficiently, and the compact design fits easily on countertops or floors. All components are dishwasher-safe for convenient cleaning.",
    features: [
      "LED light feature illuminates water stream for easy location in low-light conditions",
      "2-liter water capacity suitable for single or multiple cats and small dogs",
      "3-stage filtration system includes sponge, activated carbon, and ion-exchange resin for water purification",
      "Quiet pump operation ensures peaceful home environment without disturbing pets or owners",
      "Compact design fits easily on countertops or floors without taking excessive space",
      "Dishwasher-safe components including reservoir, pump, and filter housing for easy maintenance",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "Budget-friendly price point makes automatic hydration accessible to all pet owners",
      "Suitable for cats and small dogs who prefer running water and encourages increased water consumption"
    ],
    petType: ["cat", "dog"],
  },
  {
    id: "fountain-8",
    name: "AquaPurr Pet Fountain with UV Sterilization",
    category: "fountains",
    price: 119.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviews: 1567,
    image: "https://s.alicdn.com/@sc04/kf/H157d087b5c0c4e088bbc92e8e62b0277w.jpg?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H3e6764bfd3fa437d8dd95527f0f2a575x.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hfc1ce52db0ae4ae1a9a97476d251bbb1S.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hcd7b26c8526c4b74b17aeef594bdea97V.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hc4355751bded4a8f8f5acce1b61b92beH.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hf926aa8874364ff4a8fc05e8d061bee2f.jpg?avif=close&webp=close",
    ],
    badge: "Premium",
    shortDescription: "Advanced pet fountain with UV sterilization technology, 3-liter capacity, and multi-stage filtration for maximum water purity.",
    fullDescription: "The AquaPurr Pet Fountain with UV Sterilization represents the pinnacle of water purification technology for pets. The built-in UV-C light sterilizes water continuously, eliminating 99.9% of bacteria and viruses without chemicals. The fountain features a 3-liter capacity with a multi-stage filtration system including pre-filter, activated carbon, and ion-exchange resin. The UV sterilization runs automatically every few hours, ensuring water remains clean and safe. The fountain includes a quiet pump, low water indicator, and dishwasher-safe components. This premium fountain is ideal for pet owners who prioritize water quality and pet health.",
    features: [
      "UV-C sterilization technology eliminates 99.9% of bacteria and viruses without chemical additives",
      "Automatic UV sterilization cycles run every few hours to maintain continuous water purity",
      "3-liter water capacity suitable for single or multiple pets with extended use periods",
      "Multi-stage filtration system includes pre-filter, activated carbon, and ion-exchange resin",
      "Quiet pump operation ensures peaceful home environment without disturbing pets or owners",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "Dishwasher-safe components including reservoir, pump, and filter housing for easy maintenance",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Premium construction with durable materials designed for long-lasting performance",
      "Suitable for cats and dogs of all sizes who benefit from ultra-pure, sterilized drinking water"
    ],
    petType: ["dog", "cat"],
  },
  {
    id: "fountain-9",
    name: "iPettie Tritone Ceramic Pet Fountain",
    category: "fountains",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 1456,
    image: "https://s.alicdn.com/@sc04/kf/H5eeec619defa44048d15a6af036df9830.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/H845e2095bffb4ab8adf4a1eabdfb8b4by.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hd7e2871698e14712ab72dda638b8172cM.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H5c3e95aca974477693243968d14e84d0x.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Haffbbcc586884636886ee71c8713ce6c9.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/H6953eb607272413ba27888b1b809a180c.jpg?avif=close&webp=close",
    ],
    shortDescription: "Ceramic pet fountain with elegant design, replaceable filter, and quiet operation for stylish pet hydration solutions.",
    fullDescription: "The iPettie Tritone Ceramic Pet Fountain combines elegant design with practical functionality. The ceramic construction is naturally antimicrobial, preventing bacteria growth and keeping water fresh. The fountain features a beautiful tritone design with three water streams that create an appealing visual and auditory experience for pets. With a 1.5-liter capacity, this fountain is perfect for single or multiple cats and small dogs. The replaceable carbon filter removes bad tastes and odors, while the quiet pump ensures peaceful operation. The ceramic material is easy to clean, dishwasher-safe, and won't retain odors or stains.",
    features: [
      "Ceramic construction provides natural antimicrobial properties to prevent bacteria growth",
      "Elegant tritone design with three water streams creates appealing visual and auditory stimulation",
      "1.5-liter water capacity suitable for single or multiple cats and small dogs",
      "Replaceable carbon filter removes bad tastes, odors, and impurities from tap water",
      "Quiet submersible pump operates silently without disturbing household activities",
      "Dishwasher-safe ceramic components make cleaning and maintenance effortless",
      "Non-porous ceramic surface prevents odor retention and staining for hygienic operation",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "Durable ceramic construction resists scratches and wear for long-lasting performance",
      "Suitable for cats and small dogs who prefer running water and promotes better hydration habits"
    ],
    petType: ["cat", "dog"],
  },
  {
    id: "fountain-10",
    name: "PetSafe Drinkwell Multi-Tier Pet Fountain",
    category: "fountains",
    price: 94.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviews: 1789,
    image: "https://s.alicdn.com/@sc04/kf/H35d10e2ea5d84dd2b43b2fd47b4b2143r.png?avif=close&webp=close",
    hoverImage: "https://s.alicdn.com/@sc04/kf/Haf2dc7d61eb345e28b6ad0988b84177bD.jpg?avif=close&webp=close",
    imageGallery: [
      "https://s.alicdn.com/@sc04/kf/Hc0795c3618de4b1fb19adad9bf968720E.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hfebdda706829468cad22435a19b80568A.jpg?avif=close&webp=close",
      "https://s.alicdn.com/@sc04/kf/Hf3d2af1b9b0e4e50a9ca33ffa30a3b3ds.jpg?avif=close&webp=close",
    ],
    badge: "Popular",
    shortDescription: "Multi-tier pet fountain with cascading water design, large 100-ounce capacity, and replaceable carbon filter system.",
    fullDescription: "The PetSafe Drinkwell Multi-Tier Pet Fountain features an innovative cascading water design that creates multiple drinking levels for pets of different sizes. The fountain includes a top tier for smaller pets and a bottom reservoir for larger pets, making it ideal for multi-pet households. With a 100-ounce capacity, this fountain provides plenty of fresh, filtered water throughout the day. The replaceable carbon filter removes bad tastes and odors, while the free-falling water stream encourages pets to drink more. The quiet pump and dishwasher-safe components make maintenance simple, and the low water indicator ensures continuous operation.",
    features: [
      "Multi-tier cascading water design provides multiple drinking levels for pets of different sizes",
      "Large 100-ounce water capacity suitable for multiple pets and extended use periods",
      "Top tier design accommodates smaller pets while bottom reservoir serves larger pets",
      "Replaceable carbon filter removes bad tastes, odors, and impurities from tap water",
      "Free-falling water stream design encourages increased water consumption for better hydration",
      "Quiet submersible pump operates silently without disturbing pets or household activities",
      "Dishwasher-safe components including reservoir, tiers, and filter housing for easy cleaning",
      "Low water level indicator alerts when reservoir needs refilling to maintain continuous operation",
      "BPA-free materials ensure safe drinking water without harmful chemical exposure",
      "Ideal for multi-pet households with cats and dogs of various sizes requiring different drinking heights"
    ],
    petType: ["dog", "cat"],
  },
] as const;

export const TRUST_BADGES = [
  { icon: "Shield", label: "Secure Checkout" },
  { icon: "Headphones", label: "Fast Support" },
  { icon: "RefreshCw", label: "Easy Returns" },
  { icon: "BadgeCheck", label: "Verified Business" },
] as const;

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/shop", label: "Shop" },
  { href: "/about", label: "About" },
  { href: "/trust", label: "Why Trust Us" },
  { href: "/contact", label: "Contact" },
] as const;

export const POLICY_LINKS = [
  { href: "/policies/terms", label: "Terms & Conditions" },
  { href: "/policies/shipping", label: "Shipping Policy" },
  { href: "/policies/returns", label: "Returns & Refunds" },
  { href: "/policies/privacy", label: "Privacy Policy" },
] as const;
